name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_x86_and_amd64:
    runs-on: ubuntu-latest
    name: Build x86 and amd64 projects

    steps:
    - uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get install nasm

    - name: Install GCC with 32-bit libraries
      run: sudo apt-get install gcc gcc-multilib

    - name: Build small project (dcompl)
      run: |
        cd ${{github.workspace}}/x86/small-project
        make

    - name: Build main project (sepia) for x86
      run: |
        cd ${{github.workspace}}/x86/sepia
        make x86

    - name: Build main project (sepia) for amd64
      run: |
        cd ${{github.workspace}}/x86/sepia
        make x64

  assemble_mips:
    runs-on: ubuntu-latest
    name: Build MIPS projects

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2

    - name: Install MARS
      run: wget -P ${{github.workspace}}/mips http://courses.missouristate.edu/kenvollmar/mars/MARS_4_5_Aug2014/Mars4_5.jar

    - name: Assemble training projects
      run: |
        cd ${{github.workspace}}/mips/training
        for file in *.asm;
          do java -jar ../Mars4_5.jar a ae1 $file;
          done
        
    - name: Assemble main project (C.asm)
      run: |
        cd ${{github.workspace}}/mips/main-project
        java -jar ../Mars4_5.jar a ae1 C.asm
