name: "x86 and amd64 CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_x86_and_amd64:
    runs-on: ubuntu-latest
    name: Build x86 and amd64 projects

    steps:
    - uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get install nasm

    - name: Install GCC with 32-bit libraries
      run: sudo apt-get install gcc gcc-multilib

    - name: Build small project (dcompl)
      run: |
        cd ${{github.workspace}}/x86/small-project
        make

    - name: Build main project (sepia) for x86
      run: |
        cd ../sepia
        make x86

    - name: Build main project (sepia) for amd64
      run: |
        make x64
